#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Paths below are relative to the one-wso2 repo root; fail loudly rather than
# scattering files somewhere unexpected.
if [ ! -f "webapp/vite.config.ts" ] || [ ! -d "docs/ported-apps" ]; then
  printf 'Run this from the one-wso2 repo root (where webapp/ and docs/ live).\n' >&2
  exit 1
fi

# Resumable scratch. webapp/.gitignore ignores *.local, so re-runs remember
# what you already pasted and Enter keeps it.
ENV_FILE="webapp/mis-wizard.local"

# Findings land here. The root .gitignore reserves "My Findings*.md" for
# exactly this — its own comment says these carry "gateway URLs, Asgardeo
# client ids, group names and security observations that shouldn't be
# published."
FINDINGS="My Findings Finance MIS.md"

# Scalars, not arrays: this box runs bash 3.2, where `${#arr[@]}` on an empty
# array trips `set -u`.
CSP_PROBLEMS=""
REACH_SUMMARY=""

# csp_verdict URL — the production CSP in webapp/vite.config.ts allows
# connect-src only from *.wso2.com and *.asgardeo.io. Choreo's default gateway
# domain (*.choreoapis.dev) is NOT on that list, and a blocked request fails
# silently in the browser with no error.
csp_verdict() {
  local url="$1" name="$2" host
  host=$(printf '%s' "$url" | sed -E 's#^[a-zA-Z]+://##; s#/.*$##; s#:.*$##')
  case "$host" in
    *.wso2.com|wso2.com|*.asgardeo.io)
      printf '  %s✓ CSP ok%s  %s is inside connect-src\n' "$GREEN" "$RESET" "$host" ;;
    "")
      warn "could not read a hostname out of that URL" ;;
    *)
      printf '  %s✗ CSP BLOCKS%s %s — not in connect-src\n' "$RED" "$RESET" "$host"
      note "  webapp/vite.config.ts:31 allows only *.wso2.com and *.asgardeo.io."
      note "  In a production build this request fails with no visible error."
      CSP_PROBLEMS="${CSP_PROBLEMS}${name} ($host); " ;;
  esac
}

# probe LABEL URL PATH — does the gateway accept a One WSO2 token for this
# service? This is the blocker in docs/ported-apps/mis.md §11.1.
probe() {
  local label="$1" base="$2" path="$3" code body
  [ -n "$base" ] || { note "$label: no URL captured, skipping"; return 0; }
  body=$(mktemp)
  code=$(curl -s -m 20 -o "$body" -w '%{http_code}' \
    -H "Authorization: Bearer ${MIS_TOKEN}" \
    -H "Accept: application/json" \
    "${base%/}${path}" 2>/dev/null || printf '000')
  case "$code" in
    200) printf '  %s✓ %s → 200%s  reachable and authorized\n' "$GREEN" "$label" "$RESET"
         if command -v jq >/dev/null 2>&1; then
           head -c 600 "$body" | jq -C . 2>/dev/null | head -20 || head -c 300 "$body"
         fi ;;
    401) printf '  %s✗ %s → 401%s  token rejected — wrong tenant/audience, or the\n' "$RED" "$label" "$RESET"
         note "     gateway did not rewrite Authorization into x-jwt-assertion" ;;
    403) printf '  %s! %s → 403%s  service reached, but it refused this identity —\n' "$YELLOW" "$label" "$RESET"
         note "     the email-domain regex or the role check said no" ;;
    404) printf '  %s! %s → 404%s  reached a server, wrong base path\n' "$YELLOW" "$label" "$RESET" ;;
    000) printf '  %s✗ %s → no response%s  DNS/TLS/timeout — hostname wrong, or the\n' "$RED" "$label" "$RESET"
         note "     component is not publicly visible" ;;
    *)   printf '  %s? %s → HTTP %s%s\n' "$YELLOW" "$label" "$code" "$RESET" ;;
  esac
  REACH_SUMMARY="${REACH_SUMMARY}${label}=${code} "
  rm -f "$body"
}

add_finding() { printf '%s\n' "$1" >> "$FINDINGS"; }

banner "Finance MIS port — Choreo & Asgardeo facts"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Asgardeo: the One WSO2 application"
say "One WSO2 signs in with Asgardeo. We need the tenant and the SPA client id"
say "so the app can boot against the real IdP instead of the dev bypass."
note "A SPA client id is public, not a secret — it ships in config.js."
open_url "https://console.asgardeo.io/"
step "Pick the tenant One WSO2 uses, then Applications → the One WSO2 SPA."
step "Protocol tab: copy the Client ID."
ask ONE_WSO2_AUTH_BASE_URL "Asgardeo base URL [https://api.asgardeo.io/t/wso2]:"
[ -n "$ONE_WSO2_AUTH_BASE_URL" ] || ONE_WSO2_AUTH_BASE_URL="https://api.asgardeo.io/t/wso2"
ask ONE_WSO2_AUTH_CLIENT_ID "Client ID:"
write_env ONE_WSO2_AUTH_BASE_URL "$ONE_WSO2_AUTH_BASE_URL"
write_env ONE_WSO2_AUTH_CLIENT_ID "$ONE_WSO2_AUTH_CLIENT_ID"
csp_verdict "$ONE_WSO2_AUTH_BASE_URL" "Asgardeo"
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Asgardeo: does the token carry group claims?"
say "The MIS ARR service resolves privilege 987 from LDAP groups in the JWT."
say "If One WSO2's token has no groups claim, every MIS call fails"
say "authorization even when the network path is perfect."
step "Same application → User Attributes (or Protocol → Scopes)."
step "Check that 'groups' is a requested scope AND mapped into the token."
ask MIS_GROUPS_CLAIM "Is the groups claim present in the access token? (yes/no/unsure):"
write_env MIS_GROUPS_CLAIM "$MIS_GROUPS_CLAIM"
case "$MIS_GROUPS_CLAIM" in
  [Nn]*) warn "This alone will block the port. Fix it before writing MIS code." ;;
esac
pause

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Choreo: the MIS ARR backend URL"
say "Finance MIS in One WSO2 reads the ARR service alone: the Flash Dashboard"
say "stays in the MIS app (docs/adr/0005), so its Flash and Admin services are not needed."
say "Find the ARR component's invoke URL for the environment you'll point at."
open_url "https://console.choreo.dev/"
step "Open the digiops-finance project."
step "Open app_mis_arr, go to Overview (or Deploy → endpoint), and copy the"
step "  public invoke URL."
note "Paste the base URL only — no trailing /user-info."
ask ONE_WSO2_MIS_ARR_BACKEND_URL "ARR backend base URL:"
write_env ONE_WSO2_MIS_ARR_BACKEND_URL "$ONE_WSO2_MIS_ARR_BACKEND_URL"
printf '\n'
say "Checking it against the production Content-Security-Policy:"
csp_verdict "$ONE_WSO2_MIS_ARR_BACKEND_URL" "ARR"
pause

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Choreo: network visibility of the ARR component"
say "One WSO2 is a different Choreo component from app_mis_arr. If its endpoint"
say "is Project-scoped, One WSO2 cannot call it however correct the token is."
note "The sibling finance apps mostly declare Public; MIS has no committed"
note ".choreo/component.yaml, so its visibility was set in the console."
step "app_mis_arr → Deploy → endpoint → Network Visibility."
ask MIS_VISIBILITY "Visibility of the ARR endpoint (e.g. Public or Organization):"
write_env MIS_VISIBILITY "$MIS_VISIBILITY"
pause

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Choreo: the LDAP groups behind privilege 987"
say "arr-backend declares these as 'configurable string[] = ?' and the values"
say "live only in Choreo config — they are in neither repo, and unlike its"
say "sibling apps MIS has no git-secret entry either."
warn "987 also means 'every authenticated user' in One WSO2's own privilege"
warn "table. Reading MIS access off One WSO2 capabilities hands company-wide"
warn "revenue to every employee. The MIS gate must call the ARR backend itself."
step "app_mis_arr → Deploy → Configs & Secrets (or the Config.toml mount)."
step "Find arrDashboardUserRoles."
ask MIS_ARR_ROLES "arrDashboardUserRoles (comma separated):"
write_env MIS_ARR_ROLES "$MIS_ARR_ROLES"
pause

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "The blocker: can a One WSO2 token actually call this service?"
say "This is docs/ported-apps/mis.md §11.1, the one question no amount of code"
say "reading settles. We need a live access token issued to the One WSO2 app."
note "Get one from a browser session on a working One WSO2: DevTools → Network"
note "→ any backend call → Request Headers → copy the value after 'Bearer '."
warn "The token is used for these probes only. It is never written to disk."
ask_secret MIS_TOKEN "Paste the access token (input hidden, Enter to skip):"
if [ -n "${MIS_TOKEN:-}" ]; then
  printf '\n'
  probe "ARR /user-info" "$ONE_WSO2_MIS_ARR_BACKEND_URL" "/user-info"
  printf '\n'
  note "curl ignores CORS and CSP. A 200 here proves the GATEWAY accepts the"
  note "token; it does not prove a browser will allow the call. The CSP verdict"
  note "in stage 3 is the other half of that answer."
else
  note "Skipped. The port stays blocked until this is answered."
  REACH_SUMMARY="skipped"
fi
pause

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "What does /user-info return for a non-MIS employee?"
say "This decides whether the MIS gate can show an honest 'you don't have"
say "access' state, or must treat a refusal as absence. Marketing Ops returns"
say "200 with authorized:false; a 403 would need different handling."
say ""
say "It needs a token for someone WITHOUT MIS access — a colleague, or your own"
say "account with the groups removed. Skip if you can't get one now."
ask MIS_NONUSER_BEHAVIOUR "200-with-empty-privileges / 403 / unknown:"
write_env MIS_NONUSER_BEHAVIOUR "$MIS_NONUSER_BEHAVIOUR"
pause

# ── Write the outputs ──────────────────────────────────────────────────────
_clear
printf '\n%s%s  Writing results%s\n\n' "$BOLD" "$BLUE" "$RESET"

cat > webapp/public/config.js <<CFG
// Local runtime config for the One WSO2 webapp.
// Gitignored (webapp/.gitignore:26) — never commit this file.
// Generated by mis-port-facts.wizard.sh.
window.config = {
  ONE_WSO2_AUTH_BASE_URL: "${ONE_WSO2_AUTH_BASE_URL}",
  ONE_WSO2_AUTH_CLIENT_ID: "${ONE_WSO2_AUTH_CLIENT_ID}",
  ONE_WSO2_AUTH_SIGN_IN_REDIRECT_URL: "http://localhost:3000",
  ONE_WSO2_AUTH_SIGN_OUT_REDIRECT_URL: "http://localhost:3000",

  // Finance MIS — the ARR service alone; the Flash Dashboard stays in the MIS
  // app (docs/adr/0005). The URL is not enough to show MIS: every MIS screen is
  // behind the "mis" preview flag too. See docs/ported-apps/mis.md §6.
  ONE_WSO2_MIS_ARR_BACKEND_URL: "${ONE_WSO2_MIS_ARR_BACKEND_URL}",
  ONE_WSO2_PREVIEW_FEATURES: { mis: true },
};
CFG
printf '  %s✓ wrote%s webapp/public/config.js\n' "$GREEN" "$RESET"

add_finding ""
add_finding "## Finance MIS port — Choreo & Asgardeo facts"
add_finding ""
add_finding "Collected by mis-port-facts.wizard.sh. Answers docs/ported-apps/mis.md §11.1-11.4."
add_finding ""
add_finding "| Fact | Value |"
add_finding "| --- | --- |"
add_finding "| Asgardeo base URL | \`${ONE_WSO2_AUTH_BASE_URL}\` |"
add_finding "| One WSO2 client id | \`${ONE_WSO2_AUTH_CLIENT_ID}\` |"
add_finding "| groups claim in token | ${MIS_GROUPS_CLAIM} |"
add_finding "| ARR backend | \`${ONE_WSO2_MIS_ARR_BACKEND_URL}\` |"
add_finding "| Network visibility (ARR) | ${MIS_VISIBILITY} |"
add_finding "| arrDashboardUserRoles (privilege 987) | ${MIS_ARR_ROLES} |"
add_finding "| /user-info for a non-MIS employee | ${MIS_NONUSER_BEHAVIOUR} |"
add_finding "| Live probe result | ${REACH_SUMMARY} |"
add_finding "| CSP problems | ${CSP_PROBLEMS:-none} |"
add_finding ""
printf '  %s✓ appended%s %s\n' "$GREEN" "$RESET" "$FINDINGS"

# ── Summary ────────────────────────────────────────────────────────────────
printf '\n%s%s  Where the port stands%s\n\n' "$BOLD" "$GREEN" "$RESET"
if [ -n "$CSP_PROBLEMS" ]; then
  warn "CSP blocks: ${CSP_PROBLEMS}"
  note "  Add those origins to connect-src in webapp/vite.config.ts:31, or move"
  note "  the services behind a *.wso2.com domain. Until then production builds"
  note "  fail silently while dev works fine."
else
  printf '  %s✓%s every captured URL is inside the production CSP\n' "$GREEN" "$RESET"
fi
printf '  %s·%s reachability: %s\n' "$DIM" "$RESET" "${REACH_SUMMARY:-not tested}"
printf '\n'
note "Next: fold these into docs/ported-apps/mis.md §11 and close the open"
note "questions, then the ARR Build tracer bullet is unblocked."
note "The token was never persisted. webapp/mis-wizard.local holds the rest"
note "(gitignored via *.local); delete it when you're done."
printf '\n'
